### ISSUE TITLE
Enhancement: Lua bindings

### ISSUE THREAD

**Issue by 0joshuaolson1** [TACC/GraviT#1]
Specifically, I would love to try using this with [Terra](http://terralang.org).

**Comment by pnav** [comment]
Great idea, Joshua. Would you have bandwidth to take this on?

**Comment by 0joshuaolson1** [comment]
I'll look into GraviT more to see if I understand it first.

**Comment by 0joshuaolson1** [comment]
This needs a lot more documentation before it'll get community interest. Sorry.
