### ISSUE TITLE
GregSpray fails to install

### ISSUE THREAD

**Issue by ngoldbaum** [TACC/GraviT#12]
OK, I got past the build issue in #11 and was able to successfully build GregSpray. Now when I try to install I get the following error:

```
$ make install
[  3%] Built target ospray_common
[ 49%] Built target ospray
[ 50%] Built target ospTutorialC
[ 51%] Built target ospTutorial
[ 52%] Built target ospray_module_opengl_util
[ 53%] Built target ospray_xml
[ 55%] Built target ospray_importer
[ 56%] Built target ospray_tfn
[ 60%] Built target ospray_minisg
[ 64%] Built target ospray_commandline
[ 66%] Built target ospCvtParaViewTfcn
[ 66%] Built target ospray_script
[ 67%] Built target ospBenchmark
[ 69%] Built target ospray_glut3d
[ 70%] Built target ospGlutViewer
[ 79%] Built target ospray_sg
[ 85%] Built target ospQtViewer
[100%] Built target ospVolumeViewer
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/ospray.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPExternalRays.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPDataType.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPTexture.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/LICENSE.txt
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/CHANGELOG.md
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/README.md
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libembree.2.16.5.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPConfig.h
-- Installing: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.1.1.2.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.0.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/AffineSpace.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/box.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/common.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/constants.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/FileName.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/intrinsics.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/library.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/LinearSpace.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/malloc.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/math.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/platform.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/Quaternion.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/RefCount.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/sysinfo.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/thread.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/vec.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libtbb.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libtbbmalloc.dylib
CMake Error at builddir/ospray/intel64/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/Users/goldbaum/Documents/GraviT/third-party/GregSpray/ospray/TBB_LIBRARY_DEBUG-NOTFOUND".
Call Stack (most recent call first):
  cmake_install.cmake:66 (include)
```

Perhaps I needed to install the TBB library before building Embree? I built Embree from source using the submodule in the GraviT repo.

**Comment by pnav** [comment]
Ah, yes, please install TBB and build both Embree and GregSpray against it.  I’m surprised embree didn’t complain, but either way GregSpray / OSPRay certainly needs it.

On Dec 8, 2017, at 3:23 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I got past the build issue in #11<https://github.com/TACC/GraviT/issues/11> and was able to successfully build. Now when I try to install I get the following error:

$ make install
[  3%] Built target ospray_common
[ 49%] Built target ospray
[ 50%] Built target ospTutorialC
[ 51%] Built target ospTutorial
[ 52%] Built target ospray_module_opengl_util
[ 53%] Built target ospray_xml
[ 55%] Built target ospray_importer
[ 56%] Built target ospray_tfn
[ 60%] Built target ospray_minisg
[ 64%] Built target ospray_commandline
[ 66%] Built target ospCvtParaViewTfcn
[ 66%] Built target ospray_script
[ 67%] Built target ospBenchmark
[ 69%] Built target ospray_glut3d
[ 70%] Built target ospGlutViewer
[ 79%] Built target ospray_sg
[ 85%] Built target ospQtViewer
[100%] Built target ospVolumeViewer
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/ospray.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPExternalRays.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPDataType.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPTexture.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/LICENSE.txt
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/CHANGELOG.md
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/share/doc/OSPRay/README.md
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libembree.2.16.5.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/OSPConfig.h
-- Installing: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.1.1.2.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.0.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libospray_common.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/AffineSpace.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/box.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/common.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/constants.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/FileName.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/intrinsics.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/library.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/LinearSpace.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/malloc.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/math.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/platform.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/Quaternion.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/RefCount.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/sysinfo.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/thread.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/include/ospray/SDK/../ospcommon/vec.h
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libtbb.dylib
-- Up-to-date: /Users/goldbaum/Documents/GraviT/third-party/GregSpray/install/lib/libtbbmalloc.dylib
CMake Error at builddir/ospray/intel64/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/Users/goldbaum/Documents/GraviT/third-party/GregSpray/ospray/TBB_LIBRARY_DEBUG-NOTFOUND".
Call Stack (most recent call first):
  cmake_install.cmake:66 (include)


Perhaps I needed to install the TBB library before building Embree? I built Embree from source using the submodule in the GraviT repo.

**Comment by ngoldbaum** [comment]
OK cool. I'm updating the installation instructions as I go so hopefully the next person will have fewer issues :)

**Comment by pnav** [comment]
Great idea, and thanks for that Nathan!  It really helps to have non-TACC folks on board to protect from situations like this, since our systems typically have TBB already installed, so we can fall into taking it for granted. Thanks for keeping us honest ;-)

Paul

On Dec 8, 2017, at 3:25 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


OK cool. I'm updating the installation instructions as I go so hopefully the next person will have fewer issues :)

**Comment by ngoldbaum** [comment]
Ah, actually I *do* have TBB installed, but not a debug build. Homebrew doesn't make it straightforward to do a debug build. Is it really necessary to have one or can we bypass the need for the debug build of TBB in GregSpray?

**Comment by pnav** [comment]
You should be able to bypass. I also believe the ‘Debug’ is just the project default, which perhaps should be changed to ‘Release’ (or RelWithDbgInfo)

On Dec 8, 2017, at 3:28 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, actually I do have TBB installed, but not a debug build. Homebrew doesn't make it straightforward to do a debug build. Is it really necessary to have one or can we bypass the need for the debug build of TBB in GregSpray?
