### ISSUE TITLE
Unable to build GraviT on Linux with GNU toolchain

### ISSUE THREAD

**Issue by ngoldbaum** [TACC/GraviT#15]
Currently the build is failing with the following output: https://gist.github.com/ngoldbaum/8a0c53ca94b03b2e6b1af61dcc5dc636

One concrete issue I see in the output is this:

```
/home/goldbaum/GraviT/src/gvt/render/actor/Ray.h:149:17: error: member 'glm::vec3 gvt::render::actor::Ray::<anonymous union>::<anonymous struct>::origin' with constructor not allowed in anonymous aggregate
```

Apparently gcc doesn't like anonymous structs with constructors. There also appear to be a large number of template-related errors.

**Comment by semeraro** [comment]
I have seen this too. I think naming the union and struct will make the problem go away but I dont know what kind of cascading error will be generated by doing that.

**Comment by pnav** [comment]
Doing a bit of sleuthing, the nameless struct allows us to use usual ray object member access (ray.origin, ray.direction, etc) but the union also allows us to easily memcpy these for ray movement, rather than iterating across each member.

Nathan, it appears that the GNU compiler actually should allow this. What version are you using on BW, and are you passing any additional flags?

**Comment by ngoldbaum** [comment]
Here's my compiler version information:

```
gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I don't think I'm passing any additional flags, I'm more or less following the instructions in the readme.

**Comment by ngoldbaum** [comment]
BTW, this isn't on Blue Waters. I wasn't able to compile GregSpray on Blue Waters and eventually moved to another linux host where I hit this error.

**Comment by pnav** [comment]
ah, kk, I am able to reproduce on GCC 7.1.0 on S2

**Comment by semeraro** [comment]
Made some changes to the gravit code to address this problem. Changed Ray.h and fixed all the cascading errors in the gravit code. Now I am chasing problems in the embree-shaders code. I am recompiling that with gcc in hopes the problems will go away. I am seeing some strange int narrowing error. Its in an sse related header 

` /work/01197/semeraro/stampede2/Projects/GraviT/third-party/embree-shaders/embree-shaders/common/math/../simd/sse_special.h:61:82: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
   static const ALIGN16_BEG Type _ps_##Name[4] ALIGN16_END = { Val, Val, Val, Val } `

**Comment by semeraro** [comment]
I think I have resolved the errors that caused GraviT to not compile under gnu. I merged the fixes into dev. It should now be possible to build and execute the code with the gnu compilers. Do a fresh pull and use the dev branch.

**Comment by semeraro** [comment]
This is no longer broke. I  fixed the code and can compile with gcc.
