### ISSUE TITLE
pygvt assumes it's being built with the intel compilers

### ISSUE THREAD

**Issue by ngoldbaum** [TACC/GraviT#9]
The `pygvt` `setup.py` file adds `irc` and `irf` to the list of libraries to link against. This is problematic if you are trying to build pygvt on a system that does not have the intel compilers installed. See https://github.com/TACC/GraviT/blob/cf8e829ec51e89b4da9728114f87e61d736398d1/pygvt/setup.py#L80-L81

I've removed these two libraries in my local copy of `pygvt` but am unsure of a more generic fix. I guess we need to somehow detect that someone is trying to build with the intel compilers and add the intel runtime libraries then.

**Comment by jgbarbosa** [comment]
I will probably add a file on the GVT install that places the dependencies, it will be easier.

That way we can just include it from python.


On Oct 18, 2017, at 2:03 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


The pygvt setup.py file adds irc and irf to the list of libraries to link against. This is problematic if you are trying to build pygvt on a system that does not have the intel compilers installed. See https://github.com/TACC/GraviT/blob/cf8e829ec51e89b4da9728114f87e61d736398d1/pygvt/setup.py#L80

I've removed these two libraries in my local copy of pygvt but am unsure of a more generic fix. I guess we need to somehow detect that someone us trying to build with the intel compilers and add the intel runtime libraries then.

**Comment by ngoldbaum** [comment]
Another similar issue: the setup.py file looks for `mpicxx` but OpenMPI instead calls this library `libmpi_cxx`.

**Comment by pnav** [comment]
Thanks for noting this, Nathan. Please file this as a separate issue so we can make sure it’s tracked and addressed.

Paul

On Oct 18, 2017, at 2:19 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Another similar issue: the setup.py file looks for mpicxx but OpenMPI instead calls this library libmpi_cxx.

**Comment by ngoldbaum** [comment]
Fixed by #16.
